In [38]:
import torch
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Tensors

In [2]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.0101, 0.8592, 0.8454, 0.3481],
         [0.7420, 0.2798, 0.5717, 0.9256],
         [0.6583, 0.9840, 0.0978, 0.2521]]),
 torch.float32)

In [3]:
tensor_from_array = torch.tensor(np.array([
     [1, 2, 3],
     [4, 5, 6]
     ]))
tensor_from_array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [4]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [5]:
float_32_tensor = torch.rand(size=(3,4))
float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor

tensor([[0.1947, 0.4412, 0.9946, 0.0941],
        [0.1399, 0.0295, 0.8550, 0.9980],
        [0.9619, 0.6045, 0.1818, 0.2209]], dtype=torch.float16)

In [6]:
evens_to_100 = torch.arange(start=2, end=101, step=2)
evens_to_100

tensor([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,
         30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
         58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,
         86,  88,  90,  92,  94,  96,  98, 100])

In [7]:
torch.ones_like(input=evens_to_100)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1])

In [8]:
tensor_transposed = torch.transpose(tensor_from_array,-2, 1)
tensor_transposed, tensor_from_array.T

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [9]:
torch.matmul(tensor_from_array, tensor_transposed)
# tensor_from_array @ tensor_transposed

tensor([[14, 32],
        [32, 77]])

In [10]:
evens_to_100.min(), evens_to_100.max(), torch.mean(evens_to_100.type(torch.float32)), evens_to_100.sum()

(tensor(2), tensor(100), tensor(51.), tensor(2550))

In [11]:
tensor = torch.arange(10, 100, 10)
tensor, tensor.argmin(), tensor.argmax()

(tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(0), tensor(8))

# Reshaping, stacking, squeezing and unsqueezing

* ##### torch.reshape(input, shape)	 - Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
* ##### Tensor.view(shape)	- Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
* ##### torch.stack(tensors, dim=0)	 - Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
* ##### torch.squeeze(input)	- Squeezes input to remove all the dimenions with value 1.
* ##### torch.unsqueeze(input, dim)	 - Returns input with a dimension value of 1 added at dim.
* ##### torch.permute(input, dims)	- Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [12]:
tensor.shape

torch.Size([9])

In [13]:
t_reshaped = tensor.reshape(3,3)
t_reshaped

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [14]:
t_view = tensor.view(3,3)
t_view[:,0] = 0
tensor, t_view  # view of tensor shares the same memory as the original input

(tensor([ 0, 20, 30,  0, 50, 60,  0, 80, 90]),
 tensor([[ 0, 20, 30],
         [ 0, 50, 60],
         [ 0, 80, 90]]))

In [15]:
torch.stack([tensor, tensor, tensor], dim=0)   # torch.vstack

tensor([[ 0, 20, 30,  0, 50, 60,  0, 80, 90],
        [ 0, 20, 30,  0, 50, 60,  0, 80, 90],
        [ 0, 20, 30,  0, 50, 60,  0, 80, 90]])

In [16]:
torch.stack([tensor, tensor, tensor], dim=1) # torch.hstack

tensor([[ 0,  0,  0],
        [20, 20, 20],
        [30, 30, 30],
        [ 0,  0,  0],
        [50, 50, 50],
        [60, 60, 60],
        [ 0,  0,  0],
        [80, 80, 80],
        [90, 90, 90]])

In [17]:
torch.vstack([tensor, tensor, tensor])

tensor([[ 0, 20, 30,  0, 50, 60,  0, 80, 90],
        [ 0, 20, 30,  0, 50, 60,  0, 80, 90],
        [ 0, 20, 30,  0, 50, 60,  0, 80, 90]])

In [18]:
x = torch.zeros(2, 1, 2, 1, 2)
x, x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [19]:
y = torch.squeeze(x, 1)
y, y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [20]:
y = torch.squeeze(x, (1, 2, 3))
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [21]:
y = torch.squeeze(x)
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [22]:
x = torch.tensor([1, 2, 3, 4])
x

tensor([1, 2, 3, 4])

In [23]:
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [24]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [25]:
z = torch.randint(low=0, high=50, size=(2, 3, 5))
z, z.size()

(tensor([[[37, 14, 42, 15,  7],
          [14, 44, 17, 47, 26],
          [21, 47,  6,  1, 20]],
 
         [[23, 29, 46, 21, 25],
          [22, 31, 49, 10, 29],
          [12, 47, 34, 46,  6]]]),
 torch.Size([2, 3, 5]))

In [26]:
z_permuted = torch.permute(z, (2, 0, 1))
z_permuted, z_permuted.size()

(tensor([[[37, 14, 21],
          [23, 22, 12]],
 
         [[14, 44, 47],
          [29, 31, 47]],
 
         [[42, 17,  6],
          [46, 49, 34]],
 
         [[15, 47,  1],
          [21, 10, 46]],
 
         [[ 7, 26, 20],
          [25, 29,  6]]]),
 torch.Size([5, 2, 3]))

In [27]:
z[0,0,0] = 100
z, z_permuted   # shares the same memory as the original input

(tensor([[[100,  14,  42,  15,   7],
          [ 14,  44,  17,  47,  26],
          [ 21,  47,   6,   1,  20]],
 
         [[ 23,  29,  46,  21,  25],
          [ 22,  31,  49,  10,  29],
          [ 12,  47,  34,  46,   6]]]),
 tensor([[[100,  14,  21],
          [ 23,  22,  12]],
 
         [[ 14,  44,  47],
          [ 29,  31,  47]],
 
         [[ 42,  17,   6],
          [ 46,  49,  34]],
 
         [[ 15,  47,   1],
          [ 21,  10,  46]],
 
         [[  7,  26,  20],
          [ 25,  29,   6]]]))

In [35]:
# Tensor from numpy array
a = np.arange(1, 8)
t = torch.from_numpy(a).type(torch.float32)
a, t

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [37]:
a1 = t.numpy()
a1

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [42]:
# Set the random seed
RANDOM_SEED=42
torch.random.manual_seed(RANDOM_SEED)
tn = torch.randn(2, 3)
tn

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])

In [45]:
# Check for GPU access with PyTorch
torch.cuda.is_available()
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'